### ISSUE TITLE
timeout_system() is not exported by default, so the first example fails

### ISSUE THREAD

**Issue by OpossumPetya** [nrdvana/perl-Proc-Background#10]
First example in doc fails with `Undefined subroutine &main::timeout_system called at test.pl line 7.`

    use Proc::Background;
    timeout_system($seconds, $command, $arg1, $arg2);
    timeout_system($seconds, "$command $arg1 $arg2");

I guess the function is not exported, and the example should updated to something like `use Proc::Background 'timeout_system';`

Thank you for this module!

**Comment by nrdvana** [comment]
Released a new version with corrected documentation.
