### ISSUE TITLE
Expecting of getting result faster than timeout

### ISSUE THREAD

**Issue by Fvl14** [nrdvana/perl-Proc-Background#8]
Hi @nrdvana, 

I am using this module in my development process. It looks like I catch and issue due to the last release.
The expectation is that the current process should receive result back from the child process immediately and do not wait till timeout finished. It was working in the previous release.

**Scenario**
_Perl 5.24 on Windows 10(64bit)_
duration of 'testScriptWaitingTime.pl' is 15 sec
timeout is 30 sec
**FAILED**: timeout_system returned result after 30 sec
 **EXPECTED**: timeout_system should return result after 15 sec

==========================================
Test scripts:
**test.pl**
use strict;
use warnings;
use Proc::Background;
use Capture::Tiny "capture_merged";
use POSIX ":sys_wait_h";

my $cmdLine = 'perl testScriptWaitingTime.pl';
my ($success, $timeout_reached);
my $merged_stdout_and_stderr = capture_merged {
    ($success, $timeout_reached) = Proc::Background::timeout_system(30, $cmdLine);
 };

 print "\nERROR = $merged_stdout_and_stderr\n";
 print "\nsuccess = $success\n";
 print "\ntimeout_reached = $timeout_reached\n";

==========================================

**testScriptWaitingTime.pl**
for ($i = 0; $i < 5; $i++) {
	print "\nSleep $i\n ";
	sleep 3;
}
print "\nEXIT\n";

==========================================

Is this a new behavior and won't be changed?
If this is a bug then could you please fix it ASAP?

Best Regards, FVL14

**Comment by nrdvana** [comment]
Sorry about that!  The intent was to make it return instantly when the program exits instead of at 1-second granularity.  I've just pushed a fix and it should appear on cpan soon.

**Comment by Fvl14** [comment]
Hi @nrdvana ,

Thank you so much for quick fix!

Best Regards, FVL14
