### ISSUE TITLE
Tests fail with space in path

### ISSUE THREAD

**Issue by TBSliver** [nrdvana/perl-Proc-Background#9]
If there is a space in the path for the main test, it fails - this is due to the quoted string tests such as https://github.com/nrdvana/perl-Proc-Background/blob/master/t/01proc.t#L149

I'd create a patch but not got the time atm, so if someone gets to it before me, then yay

**Comment by LRitzdorf** [comment]
Can confirm that this is still an issue (using the latest Strawberry Perl on Windows 11). Notably, `Proc::Background` is required by `Neovim::Ext`, the Perl interface for Neovim, and any attempt to install it will surface this issue. A fix would be highly appreciated.

**Comment by nrdvana** [comment]
I just attempted to install Strawberry perl in a path with a space but the installer stops me with "Strawberry Perl (64-bit) cannot be installed in a directory with spaces or non-ASCII characters".

How did either of you get perl installed in a way that $^X has a space in it?

(not that I don't believe you, I just need to be able to test this to know if I've fixed it)
